# Generated by Django 5.0.6 on 2024-09-29 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pango_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contratlocation',
            old_name='utilisateur',
            new_name='locataire',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='adresse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pango_app.adresse'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(default=1, max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='myuser_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='utilisateur_set', to='auth.permission'),
        ),
    ]
