# Generated by Django 5.0.6 on 2024-09-29 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pango_app', '0002_rename_utilisateur_contratlocation_locataire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='adresse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pango_app.adresse'),
        ),
    ]
