# Generated by Django 5.0.6 on 2024-09-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pango_app', '0003_alter_utilisateur_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='cellule',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
