# Generated by Django 5.0.6 on 2024-09-29 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pango_app', '0004_alter_adresse_cellule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='adresse',
            new_name='id_adresse',
        ),
    ]
