# Generated by Django 5.0.6 on 2024-10-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pango_app', '0005_rename_adresse_utilisateur_id_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienimmobilier',
            name='surface',
            field=models.CharField(max_length=10),
        ),
    ]
