# Generated by Django 5.0.6 on 2024-10-20 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pango_app', '0007_contratlocation_duree_mois'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mot_cle',
            name='locataire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mots_cles', to=settings.AUTH_USER_MODEL),
        ),
    ]
