# Generated by Django 5.0.6 on 2024-12-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pango_app', '0010_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='avenue',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='num_av',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='ville',
            field=models.CharField(default='Bukavu', max_length=255),
        ),
    ]
